### ISSUE TITLE
Package not on npm 

### ISSUE THREAD

**Issue by hadyrashwan** [hewmen/passport-twitter-oauth2#1]
Did you take down your package ?? I cant find it on npm

```
npm ERR! code E404
npm ERR! 404 Not Found: passport-twitter-oauth2@latest

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/hady/.npm/_logs/2018-09-08T17_51_41_608Z-debug.log
```

**Comment by GhostfromTexas** [comment]
This package is not available on NPM. Twitter does not support Oauth 2  for login at the moment. I originally wrote this to see if we could get it to work. Hope to complete it when OAuth 2 for login is fully supported by Twitter.

Oauth 1 strategies already exist for Twitter and Passport

**Comment by hadyrashwan** [comment]
I hope so also thanks

**Comment by demostenes1509** [comment]
+1
